extend-exclude = ["experiment", "orm/migrations/versions"]
output-format = "grouped"

[lint]
select = ["E4", "E7", "E9", "D", "F", "B", "G", "W", "T", "PTH", "TRY", "ARG", "ANN"]

unfixable = [
    "F401",   # unused import
    "F841",   # unused variable
    "ERA001", # commented out code
]

ignore = ["D100", "D2", "B010", "D400", "D415"]

# D400, D415 は日本語のドキュメンテーションスタイルに合わせて無視

[lint.pycodestyle]
max-line-length = 100

[lint.per-file-ignores]
"__init__.py" = ["D104"]
