substitutions:
  _REGION: 'asia-northeast1'
  _CONTAINER: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/backend/${REPO_NAME}-backend:${SHORT_SHA}'
  _SERVICE_NAME: '${REPO_NAME//_/-}--${BRANCH_NAME:0:4}'
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'ensure-artifact-repo'
  entrypoint: bash
  args:
    - -c
    - |
      if ! gcloud artifacts repositories describe backend \
            --location=${_REGION} >/dev/null 2>&1; then
        gcloud artifacts repositories create backend \
          --repository-format=docker \
          --location=${_REGION} \
          --description="Auto-created by Cloud Build"
      fi
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-f'
    - 'backend/Dockerfile'
    - '-t'
    - '${_CONTAINER}'
    - './backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_CONTAINER}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE_NAME}
    - '--image=${_CONTAINER}'
    - '--region=${_REGION}'
    - --max-instances=1
    - --min-instances=0
    - --port=8080
    - --ingress=all
    - --allow-unauthenticated
    - --update-secrets=GEMINI_API_KEY=dietitian__gemini_api_key:latest
