services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dietitian-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/workspace/src
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FIREBASE_ADMINSDK_JSON=${FIREBASE_ADMINSDK_JSON}
    restart: unless-stopped
