FROM python:3.12
ENV PYTHONBUFFERED=1

WORKDIR /app

RUN pip install uv

COPY pyproject.toml* poetry.lock* ./

# poetryでライブラリをインストール(pyproject.tomlがあれば)
RUN poetry config virtualenvs.in-project true
RUN if [-f pyproject.toml]; then poetry install --no-root; fi

ENTRYPOINT ["poetry", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--reload"]