name: pyright

on: [push]

jobs:
  check-types-with-pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up CPython 3.12 with uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Sync dependencies with uv
        run: uv sync --extra dev

      - name: Run Pyright
        run: uv run pyright
