name: ruff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install "ruff==0.11.11"

    - name: Lint with Ruff
      run: |
        ruff check . --output-format=github
